apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend
data:
  krakend.json: |
    {
      "version": 3,
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "name": "krakend-gateway"
    }
---


