apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
  namespace: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 2
  template:
    metadata:
      labels:
        app: krakend
    spec:
      serviceAccountName: krakend-account
      containers:
      - name: krakend
        image: devopsfaith/krakend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-c", "/etc/krakend/krakend.json" ]
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: KRAKEND_PORT
          value: "8080"
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 100Mi
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
