apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: krakend-ingressroute
  namespace: krakend
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`api.mydns.com`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: krakend-service
      port: 8000
  tls: {}
